# Generated by Django 4.1 on 2022-09-15 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[(None, ''), ('L', 'Like'), ('D', 'Dislike')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_feedback', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.BigIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('song', models.ForeignKey(help_text='Number of times this song is played.', on_delete=django.db.models.deletion.CASCADE, related_name='song_counts', to='stream.song')),
            ],
        ),
    ]
