# Generated by Django 4.1 on 2022-09-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_songfeedback_songcounter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongCounter',
            new_name='SongViews',
        ),
    ]
