# Generated by Django 4.1 on 2022-09-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_rename_songcounter_songviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songviews',
            name='song',
        ),
        migrations.DeleteModel(
            name='SongFeedback',
        ),
        migrations.DeleteModel(
            name='SongViews',
        ),
    ]
