# Generated by Django 4.1 on 2022-09-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_songviews_songfeedback'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songviews',
            unique_together={('song', 'total_views')},
        ),
    ]
