# Generated by Django 4.1 on 2022-09-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_songviews_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songviews',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='songviews',
            name='song',
            field=models.ForeignKey(help_text='Number of times this song is played.', on_delete=django.db.models.deletion.CASCADE, related_name='song_counts', to='stream.song', unique=True),
        ),
    ]
